name: nuca
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 5.1.0
  sizer: 2.0.15
  lottie: 2.6.0
  intl: 0.18.1
  flutter_custom_clippers: 2.1.0
  tap_debouncer: 2.2.0
  remixicon_updated: 1.0.2
  dotted_border: 2.1.0
  persistent_bottom_nav_bar: 5.0.2
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/navbar_icons/