name: nuca
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  google_fonts: 5.1.0
  sizer: 2.0.15
  lottie: 2.6.0
  intl: 0.18.1
  flutter_custom_clippers: 2.1.0
  tap_debouncer: 2.2.0
  remixicon_updated: 1.0.2
  dotted_border: 2.1.0
  persistent_bottom_nav_bar: 5.0.2
  flutter_xlider: 3.5.0
  chip_list: 3.0.0
  pinput: 4.0.0
  # flutter_callkit_incoming: 2.0.4+1
  # flutter_chat_bubble: 2.0.2 
  flutter_chat_ui: 1.6.10
  flutter_chat_types: 3.6.2
  image_picker: 1.0.8
  file_picker: 8.0.0+1
  mime: ^1.0.4
  open_filex: ^4.4.0
  path_provider: ^2.1.3
  uuid: ^3.0.7
  
  bubble: 1.2.1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/navbar_icons/
    - assets/json/

  fonts:
    - family: LTSaeada
      fonts:
        - asset: assets/fonts/LTSaeada-Regular.otf
          weight: 400
        - asset: assets/fonts/LTSaeada-Medium.otf
          weight: 500
        - asset: assets/fonts/LTSaeada-SemiBold.otf
          weight: 700